FROM multi-video-flow-base:amd64

# 复制生成器相关代码
COPY generator/ /app/generator/

# 创建视频目录挂载点
RUN mkdir -p /videos

# 设置默认命令
CMD ["/bin/bash"]

# docker build --platform linux/amd64 -t repo:5000/dwy/stream-generator:amd64 -f Dockerfile.generator.amd64 .