FROM multi-video-flow-base:amd64

# 复制处理器相关代码
COPY processor/ /app/processor/

# 设置默认命令
CMD ["/bin/bash"]

# docker build --platform linux/amd64 -t repo:5000/dwy/stream-processor:amd64 -f Dockerfile.processor.amd64 .