FROM multi-video-flow-base:amd64

# 复制调度器相关代码
COPY scheduler/ /app/scheduler/

# 设置默认命令
CMD ["/bin/bash"]

# docker build --platform linux/amd64 -t repo:5000/dwy/stream-scheduler:amd64 -f Dockerfile.scheduler.amd64 .